services:
  web:
    build: .
    container_name: django_web
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A ExampleProject worker -l info
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  beat:
    build: .
    container_name: celery_beat
    command: celery -A ExampleProject beat -l info
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  static_volume:
  media_volume:
