# Generated by Django 5.2.7 on 2025-10-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalsstatus',
            old_name='payment_status_align',
            new_name='rental_status_align',
        ),
        migrations.RenameField(
            model_name='rentalsstatus',
            old_name='payment_status_text',
            new_name='rental_status_text',
        ),
        migrations.RenameField(
            model_name='repairsstatus',
            old_name='payment_status_align',
            new_name='repair_status_align',
        ),
        migrations.RenameField(
            model_name='repairsstatus',
            old_name='payment_status_text',
            new_name='repair_status_text',
        ),
    ]
